AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stream S3 data access logs from CloudTrail  to CloudWatch Logs to Lambda
  to ElasticSearch.

  '
Globals:
  Function:
    Timeout: 3
Resources:
  BucketPolicy:
    Properties:
      Bucket:
        Ref: S3Bucket
      PolicyDocument:
        Statement:
        - Action: s3:GetBucketAcl
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource:
            Fn::Sub: arn:aws:s3:::${S3Bucket}
          Sid: AWSCloudTrailAclCheck
        - Action: s3:PutObject
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Resource:
            Fn::Sub: arn:aws:s3:::${S3Bucket}/AWSLogs/${AWS::AccountId}/*
          Sid: AWSCloudTrailWrite
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
  CloudTrail:
    DependsOn:
    - BucketPolicy
    Properties:
      CloudWatchLogsLogGroupArn:
        Fn::GetAtt:
        - LogGroup
        - Arn
      CloudWatchLogsRoleArn:
        Fn::GetAtt:
        - CloudTrailRole
        - Arn
      EventSelectors:
      - DataResources:
        - Type: AWS::S3::Object
          Values:
          - 'arn:aws:s3:::'
        IncludeManagementEvents: false
      IncludeGlobalServiceEvents: false
      IsLogging: true
      IsMultiRegionTrail: false
      S3BucketName:
        Ref: S3Bucket
    Type: AWS::CloudTrail::Trail
  CloudTrailRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudtrail.amazonaws.com
        Version: '2012-10-17'
      Path: /
    Type: AWS::IAM::Role
  LogGroup:
    Properties:
      RetentionInDays: 7
    Type: AWS::Logs::LogGroup
  RolePolicies:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroup}:log-stream:*
        Version: '2012-10-17'
      PolicyName: cloudtrailLogsWritePolicy
      Roles:
      - Ref: CloudTrailRole
    Type: AWS::IAM::Policy
  S3Bucket:
    Type: AWS::S3::Bucket
  S3LogStreamerToElasticSearch:
    Properties:
      CodeUri: s3://werberm-sandbox/40166478af44291560e724f89a1b3779
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
